/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as OrganizationSlugLoginRouteImport } from './routes/$organizationSlug/login'
import { Route as OrganizationSlugAppRouteRouteImport } from './routes/$organizationSlug/app/route'
import { Route as DashboardOrganizationsIndexRouteImport } from './routes/dashboard/organizations.index'
import { Route as OrganizationSlugAppIndexRouteImport } from './routes/$organizationSlug/app/index'
import { Route as DashboardOrganizationsOrganizationIdRouteImport } from './routes/dashboard/organizations.$organizationId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OrganizationSlugLoginRoute = OrganizationSlugLoginRouteImport.update({
  id: '/$organizationSlug/login',
  path: '/$organizationSlug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugAppRouteRoute =
  OrganizationSlugAppRouteRouteImport.update({
    id: '/$organizationSlug/app',
    path: '/$organizationSlug/app',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const OrganizationSlugAppIndexRoute =
  OrganizationSlugAppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationSlugAppRouteRoute,
  } as any)
const DashboardOrganizationsOrganizationIdRoute =
  DashboardOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/ready': typeof ReadyRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/todos': typeof TodosRoute
  '/$organizationSlug/app': typeof OrganizationSlugAppRouteRouteWithChildren
  '/$organizationSlug/login': typeof OrganizationSlugLoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/$organizationSlug/app/': typeof OrganizationSlugAppIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/ready': typeof ReadyRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/todos': typeof TodosRoute
  '/$organizationSlug/login': typeof OrganizationSlugLoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/$organizationSlug/app': typeof OrganizationSlugAppIndexRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/ready': typeof ReadyRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/todos': typeof TodosRoute
  '/$organizationSlug/app': typeof OrganizationSlugAppRouteRouteWithChildren
  '/$organizationSlug/login': typeof OrganizationSlugLoginRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/$organizationSlug/app/': typeof OrganizationSlugAppIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/ready'
    | '/showcase'
    | '/signup'
    | '/sitemap.xml'
    | '/todos'
    | '/$organizationSlug/app'
    | '/$organizationSlug/login'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/organizations/$organizationId'
    | '/$organizationSlug/app/'
    | '/dashboard/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/ready'
    | '/showcase'
    | '/signup'
    | '/sitemap.xml'
    | '/todos'
    | '/$organizationSlug/login'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/organizations/$organizationId'
    | '/$organizationSlug/app'
    | '/dashboard/organizations'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/ready'
    | '/showcase'
    | '/signup'
    | '/sitemap.xml'
    | '/todos'
    | '/$organizationSlug/app'
    | '/$organizationSlug/login'
    | '/dashboard/account'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/organizations/$organizationId'
    | '/$organizationSlug/app/'
    | '/dashboard/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ReadyRoute: typeof ReadyRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TodosRoute: typeof TodosRoute
  OrganizationSlugAppRouteRoute: typeof OrganizationSlugAppRouteRouteWithChildren
  OrganizationSlugLoginRoute: typeof OrganizationSlugLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/$organizationSlug/login': {
      id: '/$organizationSlug/login'
      path: '/$organizationSlug/login'
      fullPath: '/$organizationSlug/login'
      preLoaderRoute: typeof OrganizationSlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug/app': {
      id: '/$organizationSlug/app'
      path: '/$organizationSlug/app'
      fullPath: '/$organizationSlug/app'
      preLoaderRoute: typeof OrganizationSlugAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organizations/': {
      id: '/dashboard/organizations/'
      path: '/organizations'
      fullPath: '/dashboard/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/$organizationSlug/app/': {
      id: '/$organizationSlug/app/'
      path: '/'
      fullPath: '/$organizationSlug/app/'
      preLoaderRoute: typeof OrganizationSlugAppIndexRouteImport
      parentRoute: typeof OrganizationSlugAppRouteRoute
    }
    '/dashboard/organizations/$organizationId': {
      id: '/dashboard/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/dashboard/organizations/$organizationId'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrganizationsOrganizationIdRoute: typeof DashboardOrganizationsOrganizationIdRoute
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrganizationsOrganizationIdRoute:
    DashboardOrganizationsOrganizationIdRoute,
  DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OrganizationSlugAppRouteRouteChildren {
  OrganizationSlugAppIndexRoute: typeof OrganizationSlugAppIndexRoute
}

const OrganizationSlugAppRouteRouteChildren: OrganizationSlugAppRouteRouteChildren =
  {
    OrganizationSlugAppIndexRoute: OrganizationSlugAppIndexRoute,
  }

const OrganizationSlugAppRouteRouteWithChildren =
  OrganizationSlugAppRouteRoute._addFileChildren(
    OrganizationSlugAppRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ReadyRoute: ReadyRoute,
  ShowcaseRoute: ShowcaseRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TodosRoute: TodosRoute,
  OrganizationSlugAppRouteRoute: OrganizationSlugAppRouteRouteWithChildren,
  OrganizationSlugLoginRoute: OrganizationSlugLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
